add condor

diff --git a/bin/nsim-make-batch b/bin/nsim-make-batch
--- a/bin/nsim-make-batch
+++ b/bin/nsim-make-batch
@@ -9,6 +9,7 @@ from math import ceil
 import numpy
 
 import nsim
+from nsim import files
 
 from argparse import ArgumentParser
 parser=ArgumentParser(__doc__)
@@ -98,6 +99,93 @@ rm -rfv ${tmpdir}
 exit $status
 """
 
+
+
+#
+# condor templates
+#
+
+_condor_master_template="""#!/bin/bash
+function runsim {
+    echo "host: $(hostname)"
+    echo "will write to file: $output"
+
+    command=%(command)s
+    ${command} --seed ${seed} ${run} ${ngal} ${output}
+    status=$?
+
+    echo "time: $SECONDS"
+
+    if [[ $status != "0" ]]; then
+        echo "error running sim: $status"
+    fi
+
+    return $status
+}
+
+ngal=$1
+output=$2
+logfile=$3
+seed=$4
+
+run=%(run)s
+
+
+if [[ -n $_CONDOR_SCRATCH_DIR ]]; then
+    tmpdir=$_CONDOR_SCRATCH_DIR
+    export TMPDIR=$tmpdir
+else
+    tmpdir=$TMPDIR
+    mkdir -p $tmpdir
+fi
+
+pushd $tmpdir
+
+tmplog=$(basename $logfile)
+
+runsim &> ${tmplog}
+status=$?
+
+echo "moving log file ${tmplog} -> ${logfile}" >> ${tmplog}
+
+mv -fv "${tmplog}" "${logfile}" 1>&2
+
+popd
+"""
+
+_condor_submit_head="""
+Universe        = vanilla
+
+Notification    = Never
+
+# Run this exe with these args
+Executable      = %(master_script)s
+
+Image_Size       =  500000
+
+GetEnv = True
+
+kill_sig        = SIGINT
+
+#requirements = (cpu_experiment == "star") || (cpu_experiment == "phenix")
+#requirements = (cpu_experiment == "star")
+
++Experiment     = "astro"
+
+"""
+
+_condor_job_template="""
++job_name = "%(job_name)s"
+Arguments = %(ngal_per)s %(output)s %(logfile)s %(seed)d
+Queue
+"""
+
+
+
+
+
+
+
 _wq_template="""
 command: |
 
@@ -113,6 +201,8 @@ command: |
     
 job_name: "%(job_name)s"
 """
+
+
 
 
 _wq_master_template="""#!/bin/bash
@@ -232,6 +322,7 @@ class MakerBase(dict):
     def write_master(self):
         master_url=self.get_master_url()
 
+        print("writing master:", master_url)
         with open(master_url,'w') as fobj:
             text = self.get_master_text()
             fobj.write(text % self)
@@ -253,7 +344,7 @@ class MakerBase(dict):
 
         filenum=0
 
-        ngal_per, nsplit, time_hours = nsim.files.get_gal_nsplit(self)
+        ngal_per, nsplit, time_hours = files.get_gal_nsplit(self)
         self['ngal_per'] = ngal_per
 
         walltime = int(2.0 + time_hours)
@@ -264,13 +355,13 @@ class MakerBase(dict):
             seed = numpy.random.randint(0,2**31-1)
 
             ngal_tot += ngal_per
-            output = nsim.files.get_output_url(self['run'], 0, 0, itrial=isplit)
+            output = files.get_output_url(self['run'], 0, 0, itrial=isplit)
             do_write=True
             if self['missing'] and os.path.exists(output):
                 do_write=False
 
             if do_write:
-                
+
                 logfile = output.replace('.fits','.log')
                 job_name='%s-%05d' % (overall_name,isplit)
 
@@ -290,7 +381,7 @@ class MakerBase(dict):
 
     def write_script(self, filenum):
         job_url=self.get_job_url(filenum)
-        
+
         with open(job_url,'w') as fobj:
             text = self.get_job_text()
             fobj.write(text)
@@ -299,7 +390,7 @@ class MakerBase(dict):
     def make_some_dirs(self):
 
         d=self.get_batch_dir()
-        outd = nsim.files.get_output_dir(self['run'], sub='bytrial')
+        outd = files.get_output_dir(self['run'], sub='bytrial')
 
         master_url=self.get_master_url()
 
@@ -328,10 +419,10 @@ class WQMaker(MakerBase):
         return tmpdir
 
     def get_batch_dir(self):
-        return nsim.files.get_wq_dir(self['run'])
+        return files.get_wq_dir(self['run'])
 
     def get_master_url(self):
-        master_url=nsim.files.get_wq_master_url(self['run'])
+        master_url=files.get_wq_master_url(self['run'])
         return master_url
 
     def get_master_text(self):
@@ -342,7 +433,7 @@ class WQMaker(MakerBase):
         return _wq_template % self
 
     def get_job_url(self, filenum):
-        job_url=nsim.files.get_wq_job_url(self['run'],
+        job_url=files.get_wq_job_url(self['run'],
                                           filenum,
                                           missing=self['missing'])
         return job_url
@@ -352,10 +443,10 @@ class LSFMaker(MakerBase):
         return None
 
     def get_batch_dir(self):
-        return nsim.files.get_lsf_dir(self['run'])
+        return files.get_lsf_dir(self['run'])
 
     def get_master_url(self):
-        master_url=nsim.files.get_lsf_master_url(self['run'])
+        master_url=files.get_lsf_master_url(self['run'])
         return master_url
 
     def get_master_text(self):
@@ -366,17 +457,110 @@ class LSFMaker(MakerBase):
         return _lsf_template % self
 
     def get_job_url(self, filenum):
-        job_url=nsim.files.get_lsf_job_url(self['run'],
+        job_url=files.get_lsf_job_url(self['run'],
                                            filenum,
                                            missing=self['missing'])
         return job_url
+
+class CondorMaker(MakerBase):
+    def _remove_sub_files(self):
+        from glob import glob
+        d=files.get_condor_dir(self['run'])
+        flist=glob(os.path.join(d, '*.condor'))
+        for f in flist:
+            print("removing:",f)
+            os.remove(f)
+
+    def write_batch_files(self):
+        """
+        currently only one written
+        """
+        self._remove_sub_files()
+        overall_name = '-'.join( (self['run'].split('-'))[1:] )
+
+        if self['missing']:
+            overall_name += 'missing'
+
+        njobs=0
+        ngal_tot=0
+
+        filenum=0
+
+        ngal_per, nsplit, time_hours = files.get_gal_nsplit(self)
+        self['ngal_per'] = ngal_per
+
+
+        icondor=0
+        fobj=None
+
+        for isplit in xrange(nsplit):
+            if (isplit % self['jobs_per_condor_sub'])==0:
+                if fobj is not None:
+                    fobj.close()
+
+                subfile=files.get_condor_submit_script(self['run'],chunk=icondor)
+                icondor+=1
+
+                print("writing sub file",subfile)
+                fobj=open(subfile,'w')
+
+                head= _condor_submit_head % self
+                fobj.write(head)
+
+
+            seed = numpy.random.randint(0,2**31-1)
+
+            ngal_tot += ngal_per
+            output = files.get_output_url(self['run'], 0, 0, itrial=isplit)
+
+            do_write=True
+            if self['missing'] and os.path.exists(output):
+                do_write=False
+
+            if do_write:
+
+                logfile = output.replace('.fits','.log')
+                job_name='%s-%05d' % (overall_name,isplit)
+
+                self['output'] = output
+                self['logfile'] = logfile
+                self['job_name']=job_name
+                self['seed'] = seed
+
+                call=_condor_job_template % self
+                fobj.write(call)
+                fobj.write('\n')
+
+                njobs += 1
+                filenum += 1
+
+
+        print('total jobs: ',njobs)
+        print('total gals:',ngal_tot)
+
+
+
+    def get_tmpdir(self):
+        return None
+
+    def get_batch_dir(self):
+        return files.get_condor_dir(self['run'])
+
+    def get_master_url(self):
+        master_url=files.get_condor_master_url(self['run'])
+        return master_url
+
+    def get_master_text(self):
+        text = _condor_master_template % self
+        return text
+
 
 class SLRMaker(MakerBase):
     def get_tmpdir(self):
         return None
 
     def get_batch_dir(self):
-        return nsim.files.get_slr_dir(self['run'])
+        return files.get_slr_dir(self['run'])
 
     def write_master(self):
         pass
@@ -389,7 +573,7 @@ class SLRMaker(MakerBase):
 
         filenum=0
 
-        ngal_per, nsplit, time_hours = nsim.files.get_gal_nsplit(self)
+        ngal_per, nsplit, time_hours = files.get_gal_nsplit(self)
         self['ngal_per'] = ngal_per
         self['last_id'] = nsplit-1
         self['job_name'] = overall_name+'-%A-%a'
@@ -398,7 +582,7 @@ class SLRMaker(MakerBase):
         walltime = int(2.0 + time_hours)
         self['walltime'] = '%02d:00:00' % walltime
 
-        toutput = nsim.files.get_output_url(self['run'], 0, 0, itrial=0)
+        toutput = files.get_output_url(self['run'], 0, 0, itrial=0)
         output = toutput[0:-11]+'${slr_pad_id}.fits'
 
         self['output']=output
@@ -427,13 +611,13 @@ class SLRMaker(MakerBase):
         return _slr_template % self
 
     def get_job_url(self):
-        job_url=nsim.files.get_slr_job_url(self['run'])
+        job_url=files.get_slr_job_url(self['run'])
         return job_url
 
     def make_some_dirs(self):
 
         d=self.get_batch_dir()
-        outd = nsim.files.get_output_dir(self['run'], sub='bytrial')
+        outd = files.get_output_dir(self['run'], sub='bytrial')
 
         print("dir:",d)
 
@@ -455,8 +639,8 @@ def main():
     system=args.system
     run=args.run
 
-    c = nsim.files.read_config(run)
-    c['simc'] = nsim.files.read_config(c['sim'])
+    c = files.read_config(run)
+    c['simc'] = files.read_config(c['sim'])
     c['command'] = get_command()
 
     c['missing'] = args.missing
@@ -467,6 +651,8 @@ def main():
         maker=LSFMaker(c)
     elif system=='slr':
         maker=SLRMaker(c)
+    elif system=='condor':
+        maker=CondorMaker(c)
     else:
         raise ValueError("bad queue system: '%s'" % system)
     maker.go()
